### ISSUE TITLE
Error when "roslaunch ros_pytorch_yolov5 detector.launch device:=cpu view_img:=True"

### ISSUE THREAD

**Issue by aimanalimie** [Shua-Kang/ros_pytorch_yolov5#16]
May I know why this error occur?

aiman@aiman:~/catkin_ws_cv_bridge$ roslaunch ros_pytorch_yolov5 detector.launch device:=cpu view_img:=True
... logging to /home/aiman/.ros/log/13894466-7e0f-11ed-a8b6-b0fc36e80577/roslaunch-aiman-29519.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://aiman:33769/

SUMMARY
========

PARAMETERS
 * /detect_manager/agnostic_nms: True
 * /detect_manager/augment: True
 * /detect_manager/classes: None
 * /detect_manager/conf_thres: 0.25
 * /detect_manager/detected_objects_topic: detected_objects_...
 * /detect_manager/detections_image_topic: detections_image_...
 * /detect_manager/detections_results_topic: detections_result...
 * /detect_manager/device: cpu
 * /detect_manager/exist_ok: True
 * /detect_manager/image_topic: /usb_cam/image_raw
 * /detect_manager/img_size: 640
 * /detect_manager/iou_thres: 0.45
 * /detect_manager/name: exp
 * /detect_manager/project: runs/result
 * /detect_manager/publish_image: True
 * /detect_manager/save_conf: True
 * /detect_manager/save_txt: False
 * /detect_manager/source: data/images
 * /detect_manager/view_img: True
 * /detect_manager/weights: yolov5s.pt
 * /rosdistro: melodic
 * /rosversion: 1.14.13

NODES
  /
    detect_manager (ros_pytorch_yolov5/detect.py)

ROS_MASTER_URI=http://localhost:11311

process[detect_manager-1]: started with pid [29537]
Traceback (most recent call last):
  File "/home/aiman/catkin_ws_pytorch_yolov5/src/ros_pytorch_yolov5/yolov5/detect.py", line 14, in <module>
    from skimage.transform import resize
  File "/home/aiman/anaconda3/lib/python3.9/site-packages/skimage/__init__.py", line 125, in <module>
    from .util.dtype import (img_as_float32,
  File "/home/aiman/anaconda3/lib/python3.9/site-packages/skimage/util/__init__.py", line 17, in <module>
    from ._map_array import map_array
  File "/home/aiman/anaconda3/lib/python3.9/site-packages/skimage/util/_map_array.py", line 2, in <module>
    from ._remap import _map_array
  File "skimage/util/_remap.pyx", line 1, in init skimage.util._remap
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
[detect_manager-1] process has died [pid 29537, exit code 1, cmd /home/aiman/catkin_ws_pytorch_yolov5/src/ros_pytorch_yolov5/yolov5/detect.py __name:=detect_manager __log:=/home/aiman/.ros/log/13894466-7e0f-11ed-a8b6-b0fc36e80577/detect_manager-1.log].
log file: /home/aiman/.ros/log/13894466-7e0f-11ed-a8b6-b0fc36e80577/detect_manager-1*.log

**Comment by Shua-Kang** [comment]
I think it is because the version of NumPy is too old. I have tested the repo on numpy==1.19.5. I think you can try to upgrade it with `pip install --upgrade numpy`.

**Comment by aimanalimie** [comment]
@Shua-Kang sorry for late reply. I able to run it before but I'm forgot how I make it.
Now, the issue occur back.

I tried to` pip install --upgrade numpy` but it doesn't follow the requirement

**Comment by Shua-Kang** [comment]
Did you use 
```
cd ros_pytorch_yolov5/yolov5/
python3 -m pip install --upgrade pip
pip3 install -r requirements.txt
```
to install the python package?
If not, I recommend you can try to create a new python environment with anaconda and then install packages like that.

**Comment by aimanalimie** [comment]
yep, I follow all the steps.

I manage to run it now. thank you
